[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "number-conversion"
version = "1.0.1"
authors = [
  { name="pschlo", email="author@example.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
