[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "testproject_pschlo"
version = "0.0.3"
authors = [
  { name="pschlo", email="author@example.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
